# Generated by Django 3.0.6 on 2020-06-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_details',
            name='distance_from_city_center',
        ),
    ]
