# Generated by Django 3.0.4 on 2020-05-03 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Hosp_detail',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1000000)])),
                ('email', models.EmailField(max_length=50)),
                ('emergency_contact', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1000000)])),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=15)),
                ('med_history', models.CharField(max_length=1000)),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('adm_date', models.DateField()),
                ('discharge_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('test_type', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('speciality', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=10)),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('consult_hrs', models.TimeField()),
                ('opd_no', models.IntegerField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Hosp_detail')),
                ('working_days', models.ManyToManyField(to='Hospital.Days')),
            ],
        ),
        migrations.CreateModel(
            name='Conducted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=1000)),
                ('report', models.CharField(max_length=10000)),
                ('date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Tests')),
            ],
        ),
    ]
