# Generated by Django 3.0.4 on 2020-06-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_inventory',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=3),
        ),
    ]
