# Generated by Django 3.0.4 on 2020-05-29 05:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('no_of_ambulances', models.IntegerField(default=1)),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myuser.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance_Details',
            fields=[
                ('vehicle_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('pincode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('contact', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('amb_type', models.CharField(choices=[('MAB', 'Mini Ambulance'), ('FAB', 'Fully Equiped Ambulance')], max_length=3)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myuser.City')),
                ('org_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
