# Generated by Django 3.0.6 on 2020-06-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ambulance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance_details',
            old_name='org_name',
            new_name='user',
        ),
    ]
